# Generated by Django 5.2.8 on 2026-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scannedband'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcuser',
            name='private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
